# Generated by Django 5.2.3 on 2025-06-27 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField()),
                ('ano', models.DateField()),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('descricao', models.CharField(blank=True, max_length=154, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itenscompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locadora.livro')),
            ],
        ),
    ]
