# Generated by Django 5.2.3 on 2025-06-29 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locadora', '0003_cliente_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='pago')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='data de pagamento')),
                ('metodo', models.CharField(choices=[('di', 'dinheiro'), ('cr', 'crédito'), ('de', 'débito'), ('pi', 'Pix')], max_length=3, verbose_name='forma de pagamento')),
                ('entrega', models.PositiveSmallIntegerField(default=15, verbose_name='prazo de entrega')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='locadora.pedido', verbose_name='ordem de compra')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'ordering': ('-pk',),
            },
        ),
    ]
